# fp = open('text.txt', 'r')
# print(type(fp))
# print(fp.read())
# n = 0
# fp.seek(n)
# print(fp.read())
# n = 0
# fp.seek(n)
# print(fp.readline())
# print(fp.readline())
# fp.seek(0)
# for line in fp:
#     print(line, end='')
# fpb = open('text2.txt', 'w')
# print(fpb.read())
# fp.close()
# fpb.close()
fpw = open('write_here', 'w')
fpw.write('string1\n')
fpw.write('string2\n')
print(fpw.readable())
fpw.close()
fpw = open('write_here.txt', 'a+')
fpw.write('another line\n')
print(fpw.readable())
print(fpw.tell())
fpw.seek(20)
print(fpw.read(10))
fpw.close()
